url_v20: https://cti-taxii.mitre.org/taxii/
url_v21: https://cti-taxii.mitre.org/taxii/
username: vehere 
password: vehere@123
path: /usr/local/etc/ruleengine/
version: 2.1
collections:
    - CyWare:
        - Blacklisted IP:
            filename: blaclisted_ip.txt
            field: kill_chain_phases
            filter: added_after >= 2023-01-28T21:33:10.772474Z
            updation: recreate
        - ipv4-addr:
            filename: ipv4-addr.txt
            field: kill_chain_phases
            filter: added_after >= 2023-01-28T21:33:10.772474Z
        - ipv6-addr:
            filename: ipv6-addr.txt
            field: kill_chain_phases
            filter: added_after >= 2023-01-28T21:33:10.772474Z
        - url:
            filename: url.txt
            field: kill_chain_phases
            filter: added_after >= 2023-01-28T21:33:10.772474Z
        - E-mail:
            filename: e_mail.txt
            field: kill_chain_phases
            filter: added_after >= 2023-01-28T21:33:10.772474Z
        - MD5:
            filename: md5.txt
            field: kill_chain_phases
            filter: added_after >= 2023-01-28T21:33:10.772474Z
        - SHA1:
            filename: sha1.txt
            field: kill_chain_phases
            filter: added_after >= 2023-01-28T21:33:10.772474Z
        - domaiin:
            filename: domain.txt
            field: kill_chain_phases
            filter: added_after >= 2023-01-28T21:33:10.772474Z

        